# Generated by Django 4.2.3 on 2023-08-13 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 13, 22, 20, 36, 255420), verbose_name='time'),
        ),
    ]
