# Generated by Django 4.2.3 on 2023-08-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0003_alter_word_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='time',
        ),
    ]
