# Generated by Django 4.2.3 on 2023-08-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0004_remove_word_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=200),
        ),
    ]
