# Generated by Django 4.2.3 on 2023-08-15 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0007_word_image_url_alter_word_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='word',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 21, 32, 59, 496351)),
        ),
    ]
