# Generated by Django 4.2.3 on 2023-08-15 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0008_image_remove_word_image_url_alter_word_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 22, 13, 21, 271949)),
        ),
    ]
