# Generated by Django 4.2.3 on 2023-08-15 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0009_alter_image_image_alter_word_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagem',
        ),
        migrations.AlterField(
            model_name='word',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 23, 32, 59, 368596)),
        ),
    ]
